#FileName: costmap_common_params.yaml
#Copyright: 2016-2018 ROS小课堂 www.corvin.cn
#Author: corvin
#Description:
# 代价地图通用参数配置文件,就是全局代价地图和局部代价地图
# 共同都需要配置的参数,各参数意义如下:
# robot_radius: 机器人的半径

robot_radius: 0.2

obstacle_layer:
  enabled: true
  # combination_method: 1
  combination_method: 0
  # combination_method：怎么更新障碍物图层，1是最大值，0是覆盖，
  track_unknown_space: true
  # track_unknown_space:如果为假，则每个像素都具有以下两种状态之一：致命障碍物或自由状态。如果为true，则每个像素都具有以下三种状态之一：致命障碍，自由或未知。
  obstacle_range: 2.5
  raytrace_range: 3.0
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {
    sensor_frame: robot0_laser_0,
    data_type: LaserScan,
    topic: /robot0/laser_0,
    marking: true,
    clearing: true
  }

inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 0.36

static_layer:
  enabled: true